spring:
  rabbitmq:
    host: 192.168.10.117
    port: 5672
    virtual-host: / # 虚拟主机
    username: ilpvc # 用户名
    password: 123456 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息